### ISSUE TITLE
How to get cell value from JSgrid table. 

### ISSUE THREAD

**Issue by paulinacarolina** [paulinacarolina/VanillaJs#1]

**Comment by codelikeamexican** [comment]
itemTemplate: function (value, item) {
                    return $("<button>").attr("class", iconClass)
                        .attr("value", item.idOrder)
                        .attr("onclick", 'redirect(this.value)' )
                        ;
                }


function redirect(value) {

    var url = "/home/Page?param=" + value;
    window.location.href = url; 
}

**Comment by paulinacarolina** [comment]
If someone ever needs to read this :) this is how i solved it, I Implemented a regular JSgrid instance and in the particular column,  where I wanted to retrieve the value from, added the "itemTemplate" property, the key in here is the "item" which will return the Object value and you can play along with it, in this specific scenario I added the value to a button that will be created evrytime a JSGrid is invoke, I also added an onclick event on the button that will take the value and send it.
```
itemTemplate: function (value, item) {
return $("").
.attr("value", item.ValueWanted)
.attr("onclick", 'redirect(this.value)' );
}
```
